version: '3.5'

services:

  service-financial-service-web:
    image: financial-service-web:latest
    ports:
      - 6001:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-end

  service-pet-shop-web:
    image: pet-shop-web:latest
    ports:
      - 6002:80
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - back-end

  service-selo-web:
    image: selo-web:latest
    ports:
      - 6003:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-end

  service-php-web-app:
    image: php-sample-demo:latest
    ports:
      - 6004:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-end
        
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - back-end

networks:
  back-end:
    driver: overlay
