version: '3.5'

services:

  app1:
    image: sithvothykiv/nodejs-tutorial-api:latest
    ports:
      - 6004:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-end
        
  app2:
    image: sithvothykiv/php-sample-demo:latest
    ports:
      - 6004:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back-end
        
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - back-end

networks:
  back-end:
    driver: overlay
