version: '3.5'

services:

  mongodb:
    image: mongo:5.0.2
    # restart: unless-stopped
    # env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
      
  app1:
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=test_db
      - DB_PORT=27017
    stdin_open: true
    image: sithvothykiv/nodejs-tutorial-api:latest
    ports:
      - 7500:7500

    # DEPLOYMENT  
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        
  app2:
    image: sithvothykiv/php-sample-demo:latest
    ports:
      - 8000:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
           
  haproxy:
    image: sithvothykiv/haproxy:1.7-alpine
    ports:
      - 80:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        
volumes:
  db:
