version: '3.5'

services:

  service-coffee:
    image: sithvothykiv/zon-coffee-web:latest
    ports:
      - 6001:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-financial:
    image: sithvothykiv/financial-service-web:latest
    ports:
      - 6002:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-pet:
    image: sithvothykiv/pet-shop-web:latest
    ports:
      - 6003:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
           
  haproxy:
    image: sithvothykiv/haproxy:1.7
    ports:
      - 80:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        
volumes:
  db:
