name: Build & Deploy

on:
  push:
    branches:
      - "main"
      
jobs: 
  service_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        # uses: docker/build-push-action@v4
        run: |
          cd microservices/pet-shop-web
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pet-shop-web:latest . 
          docker push ${{ secrets.DOCKER_USERNAME }}/pet-shop-web:latest

  service_2:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push
          # uses: docker/build-push-action@v4
          run: |
            cd microservices/financial-service-web
            docker build -t ${{ secrets.DOCKER_USERNAME }}/financial-service-web:latest . 
            docker push ${{ secrets.DOCKER_USERNAME }}/financial-service-web:latest

