name: Build & Deploy

on:
  push:
    branches:
      - "main"
      
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./microservices/pet-shop-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pet-shop-web:v1.0.0
      - name: Deploy to Docker Swarm
        uses: docker/swarm-action@v2
        with:
          stack-name: my-stack
          compose-file: docker-compose.yml
          ssh-key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          with-registry-auth: true  
          
#       - name: Deploy to swarm
#         uses: kitconcept/docker-stack-deploy@v1.0.1
#         with:
#           remote_host: ${{ secrets.REMOTE_HOST }}
#           remote_user: ${{ secrets.REMOTE_USER }}
#           remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
#           stack_file: "stacks/docker-compose.yml"
#           stack_name: "node"

